---
- name: Ensure namespace exists
  k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ rhsso_project_name }}'
        annotations:
          openshift.io/display-name: '{{ rhsso_project_display }}'
      spec: {}

- name: Subscribe to RH-SSO Operator
  k8s:
    definition: '{{ lookup("template", "rhsso-operator.yml.j2")|from_yaml }}'
