---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Build operator image
      docker_image:
        build:
          path: '{{ project_dir }}'
          pull: no
        name: '{{ operator_image }}'
        tag: latest
        push: no
        source: build
        force_source: yes

- import_playbook: ../default/converge.yml
