---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Login to quay
      docker_login:
        registry_url: quay.io
        username: '{{ quay_user }}'
        password: '{{ quay_password }}'

    - name: Build operator image
      docker_image:
        build:
          path: '{{ project_dir }}'
          pull: no
        name: '{{ operator_image }}'
        tag: latest
        push: yes
        source: build
        force_source: yes

- import_playbook: ../default/converge.yml
