---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Login to OCP
    command: oc login $OCP_SERVER -u $OCP_USERNAME -p $OCP_PASSWORD --insecure-skip-tls-verify
