---
- name: Ensure namespace exists
  k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ crw_project_name }}'
        annotations:
          openshift.io/display-name: '{{ crw_project_display }}'
      spec: {}

- name: Get a list of operator groups
  k8s_info:
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    namespace: '{{ crw_project_name }}'
  register: operator_groups

- set_fact:
    operator_group_name: '{{ operator_groups.resources[0].metadata.name }}'
  when: operator_groups.resources

- name: Subscribe to CodeReady Workspaces
  k8s:
    definition: '{{ lookup("template", "codeready-workspaces.yml.j2")|from_yaml }}'

- name: Deploy CRW of the indicated type (tssc or devsecops)
  include_tasks: "{{ 'deploy_crw_' + crw_deployment_type + '.yml' }}"
