= DevSecOps Operator

== Overview

This repository contains the code to build a DevSecOps Operator for Kubernetes, including Red Hat OpenShift Container Platform.

The above https://docs.openshift.com/container-platform/4.5/operators/understanding/crds/crd-managing-resources-from-crds.html[CRDs] enable the following use cases:

* <<DevSecOps Workshop>>

== Use Cases
=== DevSecOps Workshop

Deploy and configure the resources required by the https://github.com/RedHatGov/devsecops-workshop-dashboard/blob/develop/tekton/workshop/content/index.md[DevSecOps workshop]. The workshop should be ready for an SA to conduct after this operator has completed execution.

== Building the Operator

There is a script `hack/operate.sh` which will download the prerequisites (operator-sdk etc.), build the operator artifacts from operator-sdk defaults, package and push the operator container image, deploy the artifacts to a Kubernetes cluster, and create a `kind: DevSecOpsWorkshop` CR to deploy an instance. You should use the help page to look at what the various options do, but for the most part if you want to deploy a DevSecOpsWorkshop to a cluster directly from this repo you could run `hack/operate.sh -d`.

Before running the script make sure to update the location of the container image to a repository you have access to. If you decide to build your own container image for the operator, make sure to update `hack/operate.conf` with an updated container image location and add the `-p` flag to `operate.sh`.

== Developer Installation Steps

The installation of the Custom Resource Definition and Cluster Role requires *cluster-admin* privileges. After that regular users with `admin` privileges on their projects (which is automatically granted to the user who creates a project) can provision the Devsecops Operator in their projects and deploy DevSecOpsWorkshops using the devsecopsworkshop.redhatgov.io Custom Resource. If you've installed the operator from the https://github.com/RedHatGov/operator-catalog[RedHatGov Operator Catalog Index] on an OLM-enabled cluster, the DevSecOps operator can be installed from the OperatorHub interface of the console.

Perform the following tasks as *cluster-admin*:

. Deploy the CustomResourceDefinition, ClusterRole, ClusterRoleBinding, ServiceAccount, and Operator Deployment:
+
[source,sh]
----
hack/operate.sh
----

. Once the Operator pod is running the Operator is ready to start creating DevSecOpsWorkshops
. To deploy the above, and also one of the `config/samples/redhatgov_v1alpha1_devsecopsworkshop*.yaml` example CustomResources:
+
[source,sh]
----
hack/operate.sh --deploy-cr
----

. To install the operator with RBAC scoped to a specific namespace, deploying a Role and RoleBinding instead of a ClusterRole and ClusterRoleBinding:
+
[source,sh]
----
hack/operate.sh --overlay=namespaced --namespace=mynamespace
----

== Custom Resources

* `DevSecOpsWorkshop` - deploys tooling, pipelines, and user resources to support the OpenShift DevSecOps workshop. For a list of related roles, see the link:roles/devsecops-workshop/[devsecops-workshop roles directory].

== Deploying a custom DevSecOpsWorkshop instance using the Operator

A DevSecOpsWorkshop instance is deployed by creating a `kind: DevSecOpsWorkshop` Custom Resource based on the DevSecOpsWorkshop Custom Resource Definition. You can see some samples in the link:config/samples/[samples directory]. If you've installed the operator from the https://github.com/RedHatGov/operator-catalog[RedHatGov Operator Catalog Index] on an OLM-enabled cluster, Custom Resource creation can be done through the console UI with embedded documentation or a form view.

. Write the definition to a file (e.g. devsecopsworkshop.yaml) and then create the DevSecOpsWorkshop instance:
+
[source,sh]
----
oc create -f ./devsecopsworkshop.yaml
----

. The operator will deploy a DevSecOpsWorkshop.
. You can validate the existence of your DevSecOpsWorkshop instance by querying for devsecopsworkshop objects:
+
[source,sh]
----
oc get devsecopsworkshops
----

== Deleting a DevSecOpsWorkshop instance

Deleting a `DevSecOpsWorkshop` object will not undeploy dependent objects. This functionality is still under construction.

== Developer Uninstalling the DevSecOps Operator

In case you wish to uninstall the DevSecOps Operator, simply delete the operator and its resources with:

[source,sh]
----
hack/operate.sh -r
----

OLM uninstallation for OLM-based operators can be handled through the UI, or by deleting the `Subscription`.
