---
- name: Create the redhatgov.io/v1alpha1.DevSecOpsWorkshop
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
    wait: yes
    wait_timeout: 1800
    wait_condition:
      type: Running
      reason: Successful
      status: "True"
  vars:
    cr_file: 'redhatgov_v1alpha1_devsecopsworkshop_molecule.yaml'
