# permissions for end users to view devsecopsworkshops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devsecopsworkshops-viewer-role
rules:
- apiGroups:
  - redhatgov.io
  resources:
  - devsecopsworkshops
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatgov.io
  resources:
  - devsecopsworkshops/status
  verbs:
  - get
