# permissions for end users to edit devsecopsworkshops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devsecopsworkshop-editor-role
rules:
- apiGroups:
  - redhatgov.io
  resources:
  - devsecopsworkshops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatgov.io
  resources:
  - devsecopsworkshops/status
  verbs:
  - get
