# permissions for end users to edit tsscpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tsscpipeline-editor-role
rules:
- apiGroups:
  - redhatgov.io
  resources:
  - tsscpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatgov.io
  resources:
  - tsscpipelines/status
  verbs:
  - get
