# permissions for end users to view tsscpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tsscpipelines-viewer-role
rules:
- apiGroups:
  - redhatgov.io
  resources:
  - tsscpipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatgov.io
  resources:
  - tsscpipelines/status
  verbs:
  - get
