# permissions for end users to edit tsscplatforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tsscplatform-editor-role
rules:
- apiGroups:
  - redhatgov.io
  resources:
  - tsscplatforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatgov.io
  resources:
  - tsscplatforms/status
  verbs:
  - get
