# permissions for end users to view tsscplatforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tsscplatforms-viewer-role
rules:
- apiGroups:
  - redhatgov.io
  resources:
  - tsscplatforms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatgov.io
  resources:
  - tsscplatforms/status
  verbs:
  - get
