---
- name: Wait for Argo CD route to be created by the Operator
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: '{{ argocd_project_name }}'
    name: argocd-server
  register: argocd_route
  until: argocd_route.resources|length > 0
  retries: 10
  delay: 30

- set_fact:
    argocd_route: '{{ argocd_route|json_query("resources[0].spec.host") }}'

- name: Wait for Argo CD to respond to requests
  uri:
    url: 'https://{{ argocd_route }}/'
    return_content: yes
    validate_certs: no
  register: argocd_endpoint
  until: argocd_endpoint.status == 200
  retries: 20
  delay: 30

- name: Grant argocd-application-controller serviceaccount self-provisioner
  k8s:
    definition: "{{ lookup('template', 'cluster-role-binding.yml.j2') }}"

- name: Create tssc service account
  k8s:
    namespace: '{{ argocd_project_name }}'
    definition: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cm
      data:
        'accounts.{{ tssc_service_account.username }}': 'apiKey, login'
