apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: osdk-test
namePrefix: osdk-

resources:
- ../../crd
- ../../rbac
- ../../manager

images:
- name: testing
  newName: testing-operator

patchesStrategicMerge:
- ../manager_image.yaml
- ../debug_logs_patch.yaml
