apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../crd
- ../../rbac
- ../../manager

namespace: osdk-system
namePrefix: osdk-

images:
- name: testing
  newName: testing-operator

patchesStrategicMerge:
- ../service_account.yaml
- ../manager_image.yaml
- ../debug_logs_patch.yaml
