apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: tssc-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Deploys and manages TSSC and dependent database.
  displayName: TSSC Operator
  icon:
  - base64data: |
      iVBORw0KGgoAAAANSUhEUgAAAWgAAAFpCAYAAACxubJwAAAACXBIWX
      MAAG66AABuugHW3rEXAAAWV0lEQVR4nO3d/VHcyBbGYenW/s9OBGYjAEewOIJlIzBEsDgC4wgWRw
      BEsEMEhgg8RLAQwXgi0K02R2V5lvns09Lbrd9TRfneupdBDN3vHPWX6qZpKgCAnv/xNwEATQQ0AI
      gioAFAFAENAKIIaAAQRUADgCgCGgBEEdAAIIqABgBRBDQAiCKgAUAUAQ0AoghoABBFQAOAKAIaAE
      QR0AAgioAGAFEENACIIqABQBQBDQCiCGgAEEVAA4AoAhoARBHQACCKgAYAUQQ0AIgioAFAFAENAK
      IIaAAQRUADgCgCGgBEEdAAIIqABgBRBDQAiCKgAUAUAQ0AoghoABBFQAOAKAIaAEQR0AAgioAGAF
      EENACIIqABQBQBDQCiCGgAEEVAA4AoAhoARBHQACCKgAYAUQQ0AIgioAFAFAENAKIIaAAQRUADgC
      gCGgBEEdAAIIqABgBRBDQAiCKgAUAUAQ0AoghoABBFQAOAKAIaAEQR0AAgioAGAFEENACIIqABQB
      QBDQCiCGgAEEVAA4AoAhoARBHQACCKgAYAUQQ0AIgioAFAFAENAKIIaAAQRUADgCgCGgBEEdAAII
      qABgBRBDQAiCKgAUAUAQ0AoghoABBFQAOAKAIaAEQR0AAgioAGAFEENACIIqABQBQBDQCiCGgAEE
      VAA4AoAhoARBHQACCKgAYAUQQ0AIgioAFAFAENAKIIaAAQRUADgCgCGgBEEdAAIIqABgBRBDQAiC
      KgAUAUAQ0AoghoABBFQAOAKAIaAEQR0AAgioAGAFG/8IdJa17Xv1ZVdVxVVftv1fnvm9zb//7Ufk
      2a5qmwtwg9mtf1if209t9D+9rkW1VVM/v/zNr/Pmmab/z90qmbpin1d+vdvK4PreEf29fvia7hwT
      rJvXUSQhs/scKgbYsnFsJvEr1LbXv83iZpj34I6AidQD61fw8GupTnqqqm1jmmA10DBjav67Ydhq
      +jAa9mYcXDlMCOQ0DvyEI5dISzgTvBKgvrGFPCumxWJZ/a1x/Cv+xjVVU31iYJ6x0Q0FvodIQL0V
      Be5dk6xg0doxxWKYev9xn+UiGsryysGb/egIBew6rlS+sMQw1feLm1oL7v58fBkxUJZ1YkpBpL7l
      N7p3dJ8bAaAf0Km+m+EL9t3NeDdQqCOgNWJFxYOOdeJKxyF6pq2uR/EdAdFsyXCVdfKCGohVnFHN
      riXyP6tWmTSwjon4cychzTixWqlwtuM1905hu6a4O/9TXBZT//wr5KrZg3uWXo48WoA7rTGT4KXM
      7QPtlt5mgnbuZ1fWEf1KuC8dY+zJK8Rzb5d1XIGLOH0bfJ0Qa0DWfc0Bl+8mwBNLrlefO6vtnyDi
      q8R6eTpplt8f/d9mcfWlscw9DarsL7fTbWYY/RncURquZ5XYcq5Qvh/B/h/fhnXtdTu7sYBWsP2w
      5vhffoxuv9sap9RjivFN7vL+FvNKY22RpVBT2v62Nb2kMwb7awyqXoatqq13/3+NZPk6a5jPi5v1
      rVXOJKoVTc717UjaaCtkrlK+G8tQOrpkuvXC72/L6zfX+gFQozwnlnoe9+tb48CsVX0FQqLh6tmi
      6ucpnX9Sxid+jbXd+TeV2HYL/e8+fhhztrk0VPIBYd0Hb7OhXanr3oHNm4adKje0SpwnKrhU0g3g
      hci5t5Xcd0gHe7TF7tMBHZlwf7Oe1xtuu0x5OqtMfKCofTkpfjFXsetN1G3g98wtx9ewxjzCx050
      zp7vGRff9e4eddh/d10jSjucX0IHAXt+i0xXuPc8VtFdRxpz0OMXQYCq9ZuJZSx6WLrKCt8UwHCL
      G7vo5YtN+xPTSn787xYJVL9reXqStoC+f7Ae7i2hPk7vsIr6Wjd/v+IFpYeyxuKV5xAT3AGN9d53
      jPQQJroNPNiphRTxnQA4Tzc+ekuMFu+wc8BvW8tCG4ogK6x3BeWEeQOsZzgG3C2VcuqQLahthueg
      pn2ZMKrbI+67FNFhXSxQR0T+H8bFuBpc+y7VQwV3SK9VIEdI/zH9mcWdFpk5c9DMkVE9JFBLSNx3
      5J+CMWdibA3hsThtBzRf1h0jRXmu/Eat4B3VM4Z32Y0LyuL3tokzutsFGV/UaVzu7AVD6Hk81yC+
      cgVPl23YfWqVP625aRjVYP4fxga6/Pcl5a1mmTnxP+mKn9PbKWdQVtFeJTog5R3OYMu9O4Sjwueh
      sCJOHru/KqoBOH88Iq5uzuUDZJPFa/sOIq29VG2VbQnRnyFB0inLNwXNrayhAm4feyYxxTeT+2Sj
      pxOIeq+bjEcK5e2uQsYZsMf4/7nI8qyHmII0UluLCqKLvhjF3Y7/fW7hJS+B7SYzh9LHE4h0LhZA
      wH11ubfGd90NORZUWWsgxoW7Hhveb3wW6HRnHurN0dnCQcm36fe/WyhVThPIpCYZn1vcPOFnQv7y
      0zspPdGHSiiiWrcVNv1nhTLckLVfqJ6jhg5Bh0CsUeTLWLBOeWLKwdZvW+5lhB3zgHyYcxh3P1Ur
      ncWDWdYsjjaASVtJfHHEMkBeuTHxxf+sCyIytZBbStn/Qcdz4vdfJlV50hj7sEL09Ib/agfKcxBO
      ub544/+sgyJBvZDHHY0MZXx5csbt++l4THYj7ajL0MkSGOUQ+xbZJgl/DO53gPJacK2jNMCec1LC
      w8K5fW0dg3s7yCcN7A+qpne8ymDWYR0PaIG6+hjU+E82b2Hv2ZYNnT6NZJr0E4b8nao9da6aNcHp
      slP8ThvFuQDrGjhOt8Jf4WAw5x0Bb34Dj8lsUuwxwq6EuncHikQ+yuM3lIJe2HcN6TvW8eq40OLF
      ukSVfQEY/EX5b9nvyhJTwzYdCwGqCCJpwjOd9V/6a8U1O9gvb6hCvi8UxD6lTS3mulx1RJE84OrC
      +fOr2cdBUtW0E7Vs+fecipn4SPcRokvHqsoAlnZ/O6Duuk/3J4VdkqWjmgPSYDnu0kMKpnRyWFdE
      8BvYg4sGfKzsLXWTucOTyhRfbDUzKg7Y2fO7xUEU9VUFRKSAuexfEazudYwfFpShPFQk51DNpjSO
      KOcE7HGjNj0v0IH4Jfcz2RLSXr4x7HE0gOg6pW0E+Rty0LG9oo/hzdoeVeSWdSQXdls025LzZfNY
      tc1fE8aZpDtd9NroKe1/Wpw5jSFeHcDyrp3vGeLLG+Hnvo2RvLHimKQxyxb1LMhAz2QEj36qiEh6
      EmcOWwmYqAXsdul2NXblyxaqN/nbWp7DhMTy5IhmbtL7Ywe692JK5aBe3R8KieB2K3mmwLx1A8+r
      7Uh19pAX1L9TysDM/u8L5ODMT6fuwzNgnoNU4iv5/qWUBmIc2KiLLEZkBsBrmSCWhbcB67TIbOJi
      JxSHuen5Dj0MlU4BokWbt7jri2A8siCUoVNNVzYRKG9EfHTRvTyA7dt0cKkY2KqaJLCmiqCkEJQ/
      raI6SdT0brA7sJN4vNAgL6Fb9HfO8jG1N0ZRDSM3vmnfqE4TnV82aWBTFr8mOyyJVEQDuM+XDmhr
      gMQjqMRYcNIA8+l+Xq0bZ4s9Rwe1GZoDIO/YvANVTWMWIwvJGBENLW8L2fcRhCuooNsHYdt+3UUx
      n24LjR/Uwjz4o+Vij8JA5Lij37edI0te8VIaWED6I9p8pEK/IgLIkzolXGoGNOkVK8JcUa6sMdKE
      ZMNkicbKcS0DGD8tz+ZYiQRg9iskFiolD9obHbIKAzRUgjseyzYfCAdpgtZXldxghpJBSVDQorOa
      igMThCGolQQTuIWmLH6XVlIKThzSEbBn8wgkJAxxyQ7f0EDwyIkEYCMRkx+OH9uQ9xUD0XxkI6xR
      OWCelxyjojShiDRmFss8l5gt+KkEZWCGhIIqQBAhrCCGmMHQENaYlDevBZekhjkhDYJGFI3xPSWG
      PwCUYCGllIFNIHhDSUEdDIBiGNsSGgkRVCGmOSe0DLPDsM/SGksYOsM0IhoHmeIHZGSKMHg2dT9k
      McdKbxIqSxTgl/Q4WAjj3PWeLRNBgGIY01YrNh8LPmBw9oe5JyDDrRyBHSWCH2KGMC2sQcCTj4Uw
      8wPEIar4jJBomjjFUCOuaTis6D7whpLIn5m0k8Su8XgWuo7NE0f+z5vQeh89g5wtiBhc6pyHs29f
      gbhpCe13X4j9cuV/WiDekT2lkerG0fRFysxN9ZJaDDcpaPEd9/wrMJt2eNN1SbR0KX9XFe1+G28i
      w2BC2kDyPb1DJCOi+xQ58Sy39VhjhiGzzj0FuyYza/ioVzK1zTV4+jQCdNc1lV1a3blb1guCMfsZ
      kg8SFcN00jcBnfgyOM+byJeIkJD5Bdz4Llq/I1drz1qFTndR3uFN57Xpg9M5FKWtS8rsMxofOIq3
      ueNI3E8l2ljSqxtxQqY6nKbjK61iuPF5k0zRmV9OjEZoHM7malgJ5Gfj8BvYaFieKwxiq/ewUgIT
      06sVkQm0VuSqqg/7CJIbwuxw8wt2smpMfBMmDfFWEtKuhlNn4cuzic58ytNvjje/bgGnyE9CjEZs
      Cj0lyW2mFJsWOkBHRZ3D9UCOniXUT+glLzNGoBHTv284anNa/ECheTMKSntoIAA7C+H7M5pVIaf6
      7UAtoOJ4kd5rh0upzSSDW8oSUK6TdWSRPSw4jt+48KByR1KZ4HHbu8iir6FbZmV+IAGBWJQvqIkO
      6f9fmYfRSV19JOT4oBPbWNADGool/HB9cSQroYsX1+oXiXKRfQNoPqMRZNSC+xKtr7tLfsEdJ5s7
      4eWz1PFXciy2z17rK1jP9Gvkz4RDxWG1NSIHpY0mseJk3T2zkribaFP9q2cCZpE7CsmDlMDv6mmB
      WSAV29vPH3Dk/kvZs0DTsMV4g4bvTYYTPANnoN6IqQzs68rqcObbH3drYt5YAOb9gXh5f6c9I0rG
      BwYqF+71CxbGOQjkNI52Fe16G4+MfhYt9NmkZm92CX7FO97Q17cHipG7aA++g5nAfDmLQ+69Mem0
      oeVMO5Ug5o4zHRd8Aa4HhjCedWwpB+Ysehi6lTW5ReTCAd0I5V9NG8ruXWOOZibOHcYlu4JuvLHh
      Pc0tVzlUEFXTnsrW/9xQaW3Y01nFuEtBbrw385XZRXtiQjH9C2dterg1zTKbY39nBuEdIa7L3yeh
      jwbQ5PxMmhgq7sky52d2GLTrEFwvlniUOaO7sNOu3RwyKH6rnKJaBtaZLXYD6Vywa2xJFwXpIwpK
      8J6dUSFAuXuSx3zKWCDp3jymnCsCKkV7Og+EI4v85C+i7BS18zkf1fCcL5wbIkC9kEtDlzHOogpJ
      dYQHiN8ZXsLNHJgGEi+4a10i8ShPMitwPDsgpo2yvvOXbUhvSot4OHQLAts16z411eH6gy7Pb4JF
      El/d7a5Kg3V1mf9B5mu8jtbJ7cKujQOW6cxwFDA/hnXtdZTBp461QpKc7WuFU8Y9dDCGk758V7TL
      qyNb4zmwsYHeuLYQu3ZzjfWnZkJbuANhcJbjH/DlXkmG4vbbz5PtGpdrc2Xlu0RBOHlYXTlzEdm9
      u5k/vb+aUfc1m1sSzLgLZbTM/x6NYfY6hcOh3hOtFk4CjCuZUwpIOP4WTH0oc8rM/NEtzJfR93zv
      WQqlwr6HYDS4qx4zdt5VJiNW0d4SnhcaGjCudW4pD+3QqH4uZKrFi4tJVDsYfuv+Y0hw0pq2Qb0N
      WPszpSPSHkY0nVdKdqTrmEbpTh3Eoc0u1cSTHVdKdq/pjoR5yrn7WxSdYBXf2YNPyc6OXbajrrTm
      GTLimr5mrs4dyy9yBVe6w61XS2d3ihL9kDOVJVzcHnHCcFl2Uf0NVLp7hIWLlU1in+tTWq2QR1mA
      Sc1/WTTbqk3HhCOHdYe0z57MeDzh1eNu+7BfONPc4u9mlJ69za3yB7RQR0lf72svW+E9SyQx+dYL
      5OWKG0PhHO/2XVW+oH9L6xHYhPykEd+konmL2fVLOsqGJB9pFX+0r0uKJVHm2d7+BPBLbK/sy+Uo
      dy63zTbaRNAO07xij7rLht2Qe51+HymzzbU0Zuht6QYcMvp7a8ra+HExd3J1dcQFf9h3Trzjpib2
      Hd6QSnPT3EtbWw2fGNEzBjD+jqx2agaY8fnNXI2mNV6jBbkQFd/ZgY817wvq1H2wASvmae1YxVZO
      1XynG8VZ53WbpEQL+w8Eq1KWiTh7Y9eq5qsLu24057HOJ3Cz7kdADSLooN6OrHTrkrgZPZFrac6G
      npa5M2nMK/vw7YAVoPFs5bV2QE9M8GurtbFgqIb53zlbcJ7cOlr2ORfnVRwmqNVYoO6IqD5z193m
      dm3D4k9z0hr8jb1oHv7koRwvkk500o2yhmFccq9gc8dDxLemxCR/gzYtlSzC111psMVrHb8bclnv
      TXk9CXD0sP52oMAV39OHks3Cp/EricnIRb4eNJ00z3vWYbf9/nWM6FTXIVqVM4pDiytGRhWedJrm
      dr7GoUAd2aNE0YD31nE11YL3SEY6cJzn2eKZntATfb6hxZ+oFqeqPQZ99ZHx6NUQV09eP8juPE23
      FzFqrmt54dwUL+ZIcQOo+p2nNjQx4niZ7SUoLPdidX5JDXOsVPEq5jE4g3AqsjFITwvEpZodj7fb
      VmeeCzzcqPJpyX2QTiJZPa3z3anVTxY82rjDqgW0LL8YZy1+fjgCyol4/OnI05mLtsffHVAJs9VB
      S/fG5bBLSxjQQX9jWWoH6wR9CP7tYxB7Yp6WpEd3gL+32vxjIJuAkBvWQkQT36oYSc2B3eZc9bxf
      tEMK9AQK9gQX1mQV1Kx6BizliBQf1swXxDML+OgN6CPWroLOMxwVurTkY72VISG/q4yLg93lkocw
      e3AQG9g05VfZbBuKDMUahIY6AjZvf12DkKlfa4JQJ6T9Y5Tmw1wonIePWdbY+eDn0eMPrVWRlzKl
      I8LNq2aKfo0R73QEA7sQ7SHrt43ENF056Q536MJPJmd3onPR8D+rzUHhlOc0BAJ2Kd5Ni+fu38e7
      hjeLeHPM06R0Q+UZFgF1ZAtMeEtkeH7nqE7bMdl/ut0x5ntoadYYsECGgAEDW6szgAIBcENACIIq
      ABQBQBDQCiCGgAEEVAA4AoAhoARBHQACCKgAYAUQQ0AIgioAFAFAENAKIIaAAQRUADgCgCGgBEEd
      AAIIqABgBRBDQAiCKgAUAUAQ0AoghoABBFQAOAKAIaAEQR0AAgioAGAFEENACIIqABQBQBDQCiCG
      gAEEVAA4AoAhoARBHQACCKgAYAUQQ0AIgioAFAFAENAKIIaAAQRUADgCgCGgBEEdAAIIqABgBRBD
      QAiCKgAUAUAQ0AoghoABBFQAOAKAIaAEQR0AAgioAGAFEENACIIqABQBQBDQCiCGgAEEVAA4AoAh
      oARBHQACCKgAYAUQQ0AIgioAFAFAENAKIIaAAQRUADgCgCGgBEEdAAIIqABgBRBDQAiCKgAUAUAQ
      0AoghoABBFQAOAKAIaAEQR0AAgioAGAFEENACIIqABQBQBDQCiCGgAEEVAA4AoAhoARBHQACCKgA
      YAUQQ0AIgioAFAFAENAKIIaAAQRUADgCgCGgBEEdAAIIqABgBRBDQAiCKgAUAUAQ0AoghoABBFQA
      OAKAIaAEQR0AAgioAGAFEENACIIqABQBQBDQCiCGgAEEVAA4AoAhoARBHQACCKgAYAUQQ0AIgioA
      FAFAENAKIIaAAQRUADgCgCGgBEEdAAIIqABgBRBDQAKKqq6v9lHg2BY1DDwQAAAABJRU5ErkJggg
      ==
    mediatype: "image/png"
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - redhatgov
  - tssc
  - devsecops
  - workshop
  links:
  - name: TSSC Operator
    url: https://github.com/redhatgov/tssc-operator
  maintainers:
  - email: aromerot@redhat.com
    name: Andres Romero
  - email: akrohg@redhat.com
    name: Andy Krohg
  maturity: alpha
  provider:
    name: RedHatGov
    url: redhatgov.io
  version: 0.0.0
