apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- redhatgov_v1alpha1_tsscplatform.yaml
- redhatgov_v1alpha1_tsscplatform_molecule.yaml
- redhatgov_v1alpha1_tsscplatform_openshift.yaml
- redhatgov_v1alpha1_devsecopsworkshop.yaml
- redhatgov_v1alpha1_devsecopsworkshop_molecule.yaml
- redhatgov_v1alpha1_devsecopsworkshop_openshift.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
