---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: osdk-system
spec:
  template:
    spec:
      containers:
        - name: manager
          image: testing
      serviceAccountName: osdk-sa
