---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.kubernetes

  tasks:
    - name: Create Namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ item }}'
      loop:
      - '{{ namespace }}'

    - import_tasks: kustomize.yml
      vars:
        state: present
