- name: Wait for Quay route to begin answering requests
  uri:
    url: 'https://{{ quay_route }}/'
    return_content: yes
    validate_certs: no
  register: quay_index
  until: '"DOCTYPE html" in quay_index.content'
  retries: 10
  delay: 30

- name: Configure Quay and RHSSO to work together
  include: quay_rhsso.yml
