- name: Wait for Quay route to begin answering requests
  uri:
    url: 'https://{{ quay_route }}/'
    return_content: yes
    validate_certs: no
  register: quay_index
  until: '"DOCTYPE html" in quay_index.content'
  retries: 10
  delay: 30

- name: Add tssc service account to Quay instance
  shell: >-
    devsecops-api quay add-user https://{{ quay_route }}
    --login-username quay --login-password password
    --usernames '{{ tssc_service_account.username }}'
    --passwords '{{ tssc_service_account.password }}'
  register: quay_users
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: quay_users.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0

- name: Create Organization for pipeline
  shell: >-
    devsecops-api quay add-org https://{{ quay_route }}
    --login-username '{{ tssc_service_account.username }}' --login-password '{{ tssc_service_account.password }}'
    --organizations platform
  register: quay_orgs
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: quay_orgs.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0

- name: Create Robot account
  shell: >-
    devsecops-api quay add-robot https://{{ quay_route }}
    --login-username '{{ tssc_service_account.username }}' --login-password '{{ tssc_service_account.password }}'
    --organization platform --robot-name '{{ tssc_service_account.username }}' --robot-description 'TSSC Platform Robot Account'
  register: quay_robot
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: quay_robot.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0

- name: Get robot token
  set_fact:
    quay_robot_token: "{{ quay_robot.stdout | regex_search('[A-Z0-9]{64}') }}"

- name: Construct docker auth object
  set_fact:
    quay_robot_docker_config: "{{ lookup('template', 'quay-docker-config.yml.j2') | from_yaml | to_json }}"

- name: Create Quay robot token secret
  k8s:
    definition: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: quay-robot-token
        namespace: '{{ quay_project_name }}'
      data:
        .dockerconfigjson: '{{ quay_robot_docker_config | b64encode }}'
      type: kubernetes.io/dockerconfigjson

- name: Configure Quay and RHSSO to work together
  include: quay_rhsso.yml
