- name: Wait for Nexus to finish being created
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: '{{ nexus_project_name }}'
    label_selectors:
      - app=nexus
  register: nexus_pod
  until: nexus_pod.resources|length > 0 and (nexus_pod.resources|first).status.phase == "Running"
  retries: 10
  delay: 30

- name: Add NexusUsers to create local rut-auth accounts
  k8s:
    namespace: '{{ nexus_project_name }}'
    definition: '{{ lookup("template", "nexususer.yml.j2")|from_yaml }}'

- name: Create tssc Service Account
  k8s:
    namespace: '{{ nexus_project_name }}'
    definition: |
      apiVersion: redhatgov.io/v1alpha1
      kind: NexusUser
      metadata:
        name: {{ tssc_service_account.username }}
      spec:
        user:
          username: {{ tssc_service_account.username }}
          password: {{ tssc_service_account.password }}
          firstName: {{ tssc_service_account.first_name }}
          lastName: {{ tssc_service_account.last_name }}
          email: {{ tssc_service_account.email }}
