- name: Wait for Nexus to finish being created
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: '{{ nexus_project_name }}'
    label_selectors:
      - app=nexus
  register: nexus_pod
  until: nexus_pod.resources|length > 0 and (nexus_pod.resources|first).status.phase == "Running"
  retries: 10
  delay: 30

- name: Add NexusUsers to create local rut-auth accounts
  k8s:
    namespace: '{{ nexus_project_name }}'
    definition: '{{ lookup("template", "nexususer.yml.j2")|from_yaml }}'

- name: Create tssc Service Account
  k8s:
    namespace: '{{ nexus_project_name }}'
    definition: |
      apiVersion: redhatgov.io/v1alpha1
      kind: NexusUser
      metadata:
        name: {{ tssc_service_account.username }}
      spec:
        user:
          username: {{ tssc_service_account.username }}
          password: {{ tssc_service_account.password }}
          firstName: {{ tssc_service_account.first_name }}
          lastName: {{ tssc_service_account.last_name }}
          email: {{ tssc_service_account.email }}

- name: Retrieve Nexus admin credentials
  k8s_info:
    api_version: v1
    kind: Secret
    namespace: '{{ nexus_project_name }}'
    name: nexus-admin-credentials
  register: nexus_admin_secret
  until: nexus_admin_secret.resources|length > 0

- set_fact:
      nexus_admin_password: "{{ nexus_admin_secret | json_query('resources[0].data.password') | b64decode }}"

- name: Change the settings on the maven-releases repo to allow artifacts to be overwritten
  shell: >-
    devsecops-api nexus update-repository
    http://nexus-bypass.{{ nexus_project_name }}.svc.cluster.local:8081
    --login-username admin --login-password '{{ nexus_admin_password }}'
    --repository-names 'maven-releases'
    --write-policy 'ALLOW'
  register: updated_nexus_repos
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: updated_nexus_repos.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0
  failed_when: updated_nexus_repos.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` failed`)]")|length > 0 or updated_nexus_repos.rc != 0

- name: Add container-image-signatures raw repository
  shell: >-
    devsecops-api nexus add-raw-repository
    http://nexus-bypass.{{ nexus_project_name }}.svc.cluster.local:8081
    --login-username admin --login-password '{{ nexus_admin_password }}'
    --repository-names 'container-image-signatures'
  register: signatures_repo
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: signatures_repo.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0
  failed_when: signatures_repo.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` failed`)]")|length > 0 or signatures_repo.rc != 0
