---
### GITEA ###

# Create organization in Gitea

# Migrate demo app repo into Gitea org

# Create webhook

### QUAY ###

# Create Organization

# (Optional) Load images into quay if disconnected

# Create a secret in OpenShift to hold the Jenkins Quay robot credentials, and link it to the jenkins ServiceAccount

# Create Demo repo ahead of time and set it to public

### NEXUS ###

# Allow overwrite in maven-releases (TBD)

# (Optional) add stuff to nexus if disconnected

### SONARQUBE ###

# Install sonar-java plugin

### ARGOCD ###

### JENKINS ###
# Create Jenkins Credential for gitea sa token?


- name: 'Set tssc-config ConfigMap to {{ cr_state }}'
  k8s:
    definition: '{{ lookup("template", "tssc-config.yml.j2") }}'
    state: '{{ cr_state }}'

- name: 'Set tssc-config-secrets Secret to {{ cr_state }}'
  k8s:
    definition: '{{ lookup("template", "tssc-config-secrets.yml.j2") }}'
    state: '{{ cr_state }}'