---
- name: Clean up remaining resources
  shell: |
    oc delete -n {{ tssc_namespace }} KeycloakUser,KeycloakClient --all
    oc delete -n {{ tssc_namespace }} all,configmap,pvc,serviceaccount,rolebinding -l app=jenkins-persistent
