---
# DevSecOpsWorkshop deployment playbook.

- hosts: localhost
  pre_tasks:
    - name: Get cluster dns
      k8s_info:
        api_version: config.openshift.io/v1
        kind: DNS
        namespace: openshift-config
        name: cluster
      register: cluster_dns
    
    - set_fact:
        cluster_name: '{{ (cluster_dns.resources|first).spec.baseDomain.split(".")[0] }}'

    - set_fact:
        openshift_base_domain: "{{ (cluster_dns.resources|first).spec.baseDomain.replace(cluster_name + '.','') }}"

    - name: Get registry pull secret
      k8s_info:
        api_version: v1
        kind: Secret
        name: "{{ devsecopsworkshop.pull_secret.name | default('pull-secret') }}"
        namespace: "{{ devsecopsworkshop.pull_secret.namespace | default('openshift-config') }}"
      register: pull_secret

    - set_fact:
        reg_rhio_pull_token: "{{ pull_secret.resources[0].data['.dockerconfigjson'] }}"

    - name: Look for default defined common variables
      include_vars: ../vars/devsecops-workshop/common.yml
      
    - name: Look for default defined devsecops variables
      include_vars: ../vars/devsecops-workshop/devsecops.yml
      
    # Individual adjustment tasks have their own toggles
    - include_role:
        name: devsecops-workshop/cluster-adjuster
  roles:
    - role: devsecops-workshop/devsecops
