---
- hosts: localhost
  pre_tasks:
    - name: Get cluster dns
      k8s_info:
        api_version: config.openshift.io/v1
        kind: DNS
        namespace: openshift-config
        name: cluster
      register: cluster_dns

    - set_fact:
        cluster_name: '{{ (cluster_dns.resources|first).spec.baseDomain.split(".")[0] }}'

    - set_fact:
        openshift_base_domain: "{{ (cluster_dns.resources|first).spec.baseDomain.replace(cluster_name + '.','') }}"
        workshop_namespace: "{{ ansible_operator_meta.namespace }}"
        rhedsord_registry_username: TODO
        rhedsord_registry_password: TODO

    - name: Set project names
      set_fact:
        argocd_project_name: '{{ workshop_namespace }}'
        crw_project_name: '{{ workshop_namespace }}'
        gitea_project_name: '{{ workshop_namespace }}'
        jenkins_project_name: '{{ workshop_namespace }}'
        mattermost_namespace: '{{ workshop_namespace }}'
        nexus_project_name: '{{ workshop_namespace }}'
        quay_project_name: '{{ workshop_namespace }}'
        rhsso_project_name: '{{ workshop_namespace }}'
        selenium_grid_project_name: '{{ workshop_namespace }}'
        sonarqube_project_name: '{{ workshop_namespace }}'

    - name: Look for default defined common variables
      include_vars: ../vars/tssc-platform/common.yml
      when: common_included is not defined or not common_included

    - fail:
        msg: Unable to continue without common variables set
      when: common_included is not defined or not common_included

    - name: Look for default defined rhedsord variables
      include_vars: ../vars/tssc-platform/rhedsord.yml
      when: rhedsord_included is not defined or not rhedsord_included

    - fail:
        msg: Unable to continue without rhedsord variables set
      when: rhedsord_included is not defined or not rhedsord_included

  roles:
    - role: tssc-platform/rhedsord
