---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tsscpipelines.redhatgov.io
spec:
  conversion:
    strategy: None
  group: redhatgov.io
  names:
    kind: TsscPipeline
    listKind: TsscPipelineList
    plural: tsscpipelines
    singular: tsscpipeline
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TsscPipeline is the Schema for the tsscpipeline API
        properties:
          apiVersion:
            description: |
              APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info:
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |
              Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info:
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of TsscPipeline
            properties:
              tsscPipeline:
                description: Defines the desired state of the TsscPipeline Deployment
                properties: {}
                type: object
            type: object
          status:
            description: Status defines the observed state of TsscPipeline
            properties:
              conditions:
                description: The conditions reported by the Ansible operator
                items:
                  properties:
                    ansibleResult:
                      description: The result reported from the last playbook run
                      properties:
                        changed:
                          description: The number of tasks that resulted in a change
                          type: integer
                        completion:
                          description: The time of completion
                          type: string
                        failures:
                          description: The number of tasks that failed
                          type: integer
                        ok:
                          description: The number of tasks that completed without
                            change
                          type: integer
                        skipped:
                          description: The number of tasks that were skipped
                          type: integer
                      type: object
                    lastTransitionTime:
                      description: The last time the playbook was invoked following
                        a watch
                      format: date-time
                      type: string
                    message:
                      description: The last message reported from the Ansible Operator
                        SDK
                      type: string
                    reason:
                      description: The reason the status was updated
                      type: string
                    status:
                      description: The boolean return value of the playbook execution,
                        as a string
                      type: string
                    type:
                      description: The type of status change event
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
