---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devsecopsworkshops.redhatgov.io
spec:
  group: redhatgov.io
  names:
    kind: DevSecOpsWorkshop
    listKind: DevSecOpsWorkshopList
    plural: devsecopsworkshops
    singular: devsecopsworkshop
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DevSecOpsWorkshop is the Schema for the devsecopsworkshop API
        properties:
          apiVersion:
            description: |
              APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info:
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |
              Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info:
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of DevSecOpsWorkshop
            type: object
            properties:
              devsecopsworkshop:
                description: Defines the desired state of the DevSecOpsWorkshop Deployment
                type: object
                properties:
                  workshopUsers:
                    description: Properties related to workshop users
                    type: object
                    properties:
                      create:
                        description: Whether the cluster oauth should be updated to create workshop users
                        type: boolean
                      numberOfUsers:
                        description: The number of users to bootstrap in workshop tooling
                        type: integer
                      workshopPassword:
                        description: The password for standard workshop user accounts
                        type: string
                      adminPassword:
                        description: The password for the workshop-admin user
                        type: string
                  pullSecret:
                    description: Pull secret used by Tekton to pull images from registry.redhat.io
                    type: object
                    properties:
                      name:
                        description: The pull secret name
                        type: string
                      namespace:
                        description: The pull secret namespace
                        type: string
          status:
            description: Status defines the observed state of DevSecOpsWorkshop
            type: object
            properties:
              conditions:
                description: The conditions reported by the Ansible operator
                type: array
                items:
                  type: object
                  properties:
                    ansibleResult:
                      description: The result reported from the last playbook run
                      type: object
                      properties:
                        changed:
                          description: The number of tasks that resulted in a change
                          type: integer
                        completion:
                          description: The time of completion
                          type: string
                        failures:
                          description: The number of tasks that failed
                          type: integer
                        ok:
                          description: The number of tasks that completed without change
                          type: integer
                        skipped:
                          description: The number of tasks that were skipped
                          type: integer
                    lastTransitionTime:
                      description: The last time the playbook was invoked following a watch
                      type: string
                      format: date-time
                    message:
                      description: The last message reported from the Ansible Operator SDK
                      type: string
                    reason:
                      description: The reason the status was updated
                      type: string
                    status:
                      description: The boolean return value of the playbook execution, as a string
                      type: string
                    type:
                      description: The type of status change event
                      type: string
        type: object
    served: true
    storage: true
    subresources:
      status: {}
