---
- name: Generate projects per-user
  k8s:
    definition: '{{ lookup("template", "project.yml.j2")|from_yaml }}'

- include_role:
    name: devsecops-workshop/quay
  when: deploy_quay
- include_role:
    name: devsecops-workshop/gitea
  when: deploy_gitea
- include_role:
    name: devsecops-workshop/sonarqube
  when: deploy_sonarqube
- include_role:
    name: devsecops-workshop/nexus
  when: deploy_nexus
- include_role:
    name: devsecops-workshop/codeready-workspaces
  when: deploy_crw
- include_role:
    name: devsecops-workshop/username-distribution
  when: deploy_username_distribution
- include_role:
    name: devsecops-workshop/rocket-chat
  when: deploy_rocketchat
- include_role:
    name: devsecops-workshop/workshop-spawner
  when: deploy_workshop

- include_role:
    name: devsecops-workshop/tekton
  when:
    - deploy_pipeline
    - pipeline_style == 'tekton'
- include_role:
    name: devsecops-workshop/tekton-pipeline
  when:
    - deploy_pipeline
    - pipeline_style == 'tekton'

- include_role:
    name: devsecops-workshop/jenkins
  when:
    - deploy_pipeline
    - pipeline_style == 'jenkins'
