apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- role.yaml
- role_binding.yaml
- ../leader_election_role.yaml
- ../leader_election_role_binding.yaml
- ../devsecops_editor_role.yaml
- ../devsecops_viewer_role.yaml
